#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: slurm/submit_performix.sh grace <queue> <scenario> [options]

Profile one foreground handoff workload with Arm Performix on a Grace node.
Supported queues are ubq, lubq, and segqueue. The submitted job ID is printed
so runs can be chained or monitored with normal Slurm commands.

Options:
  --batch-size N       Native queue batch size; omit for scalar operations
  --ubq-label LABEL    Required for ubq (default: balanced,1,page,crossbeam)
  --recipe NAME        code_hotspots (default), cpu_microarchitecture,
                       instruction_mix, or system_utilization
  --duration-secs N    Measured handoff duration (default: 30)
  --warmup-secs N      Warmup/calibration duration (default: 2)
  --tag NAME           Result directory tag (generated by default)
  --after JOBID        Depend on a build or prior profile job

Env overrides:
  ACCOUNT   BSC allocation account (default: bsc18)
  UBQ       deployed repo root (default: /gpfs/projects/$ACCOUNT/$USER/UBQ)

Examples:
  build_id=$(slurm/submit_build.sh grace)
  slurm/submit_performix.sh grace segqueue 1p1c --batch-size 256 --after "$build_id"
  slurm/submit_performix.sh grace lubq 1p1c --batch-size 256 --after "$build_id"
  slurm/submit_performix.sh grace ubq 1p1c --batch-size 256 \
    --ubq-label balanced,1,page,crossbeam --after "$build_id"
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi
if [[ $# -lt 3 ]]; then
    usage >&2
    exit 2
fi
if [[ "$1" != "grace" ]]; then
    echo "Arm Performix is currently wired only for grace; the module is not available on mn5gpp" >&2
    exit 2
fi
queue=$2
scenario=$3
shift 3

case "$queue" in
    ubq|lubq|segqueue) ;;
    *) echo "Unsupported queue: $queue (expected ubq, lubq, or segqueue)" >&2; exit 2 ;;
esac
if [[ ! "$scenario" =~ ^[1-9][0-9]*p[1-9][0-9]*c$ ]]; then
    echo "Invalid scenario: $scenario (expected, for example, 1p1c)" >&2
    exit 2
fi

batch_size=""
ubq_label=""
recipe=code_hotspots
duration_secs=30
warmup_secs=2
tag=""
after_job_id=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --batch-size) batch_size=${2:?--batch-size requires a value}; shift 2 ;;
        --ubq-label) ubq_label=${2:?--ubq-label requires a value}; shift 2 ;;
        --recipe) recipe=${2:?--recipe requires a value}; shift 2 ;;
        --duration-secs) duration_secs=${2:?--duration-secs requires a value}; shift 2 ;;
        --warmup-secs) warmup_secs=${2:?--warmup-secs requires a value}; shift 2 ;;
        --tag) tag=${2:?--tag requires a value}; shift 2 ;;
        --after) after_job_id=${2:?--after requires a job id}; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unexpected argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

case "$recipe" in
    code_hotspots|cpu_microarchitecture|instruction_mix|system_utilization) ;;
    *) echo "Unsupported recipe: $recipe" >&2; exit 2 ;;
esac
if [[ ! "$duration_secs" =~ ^[1-9][0-9]*$ ]]; then
    echo "--duration-secs must be a positive integer" >&2
    exit 2
fi
if [[ ! "$warmup_secs" =~ ^[0-9]+$ ]]; then
    echo "--warmup-secs must be a non-negative integer" >&2
    exit 2
fi
if [[ -n "$batch_size" ]] && { [[ ! "$batch_size" =~ ^[0-9]+$ ]] || ((batch_size < 2)); }; then
    echo "--batch-size must be an integer of at least 2" >&2
    exit 2
fi
if [[ "$queue" == "ubq" ]]; then
    ubq_label=${ubq_label:-balanced,1,page,crossbeam}
elif [[ -n "$ubq_label" ]]; then
    echo "--ubq-label is valid only with the ubq queue" >&2
    exit 2
fi

: "${ACCOUNT:=bsc18}"
: "${UBQ:=/gpfs/projects/$ACCOUNT/$USER/UBQ}"
batch_tag=${batch_size:-scalar}
tag=${tag:-"$queue-$scenario-batch-$batch_tag-$recipe"}
tag=$(printf '%s' "$tag" | tr -cs 'A-Za-z0-9._-' '_' | sed 's/^_*//; s/_*$//')
if [[ -z "$tag" ]]; then
    echo "--tag must contain at least one filename-safe character" >&2
    exit 2
fi

mkdir -p "$UBQ/logs" "$UBQ/performix_results/grace"
dependency_args=()
if [[ -n "$after_job_id" ]]; then
    dependency_args=(--dependency="afterok:$after_job_id")
fi

sbatch --parsable \
    --account="$ACCOUNT" \
    --qos=ngp_debug \
    --partition=ngpp \
    --nodes=1 \
    --ntasks=1 \
    --cpus-per-task=144 \
    --exclusive \
    --time=00:10:00 \
    "${dependency_args[@]+"${dependency_args[@]}"}" \
    --job-name="apx-$queue-$scenario" \
    --output="$UBQ/logs/apx-grace-%j.out" \
    --error="$UBQ/logs/apx-grace-%j.err" \
    "$UBQ/slurm/performix_grace.sbatch" \
    "$UBQ" \
    "$UBQ/artifacts/grace/bench_profile" \
    "$UBQ/performix_results/grace" \
    "$queue" \
    "$scenario" \
    "$batch_size" \
    "$ubq_label" \
    "$recipe" \
    "$duration_secs" \
    "$warmup_secs" \
    "$tag"
